In [ ]:
import pandas as pd
import numpy as np

ss = pd.read_csv('/content/Sample - Superstore.csv' ,encoding="windows-1252", on_bad_lines='skip')

ss

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,5/4/2017,5/9/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [ ]:
ss.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [ ]:
ss.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [ ]:
ss.tail()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
9989,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.248,3,0.2,4.1028
9990,9991,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.960,2,0.0,15.6332
9991,9992,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.576,2,0.2,19.3932
9992,9993,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.600,4,0.0,13.3200
9993,9994,CA-2017-119914,5/4/2017,5/9/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.160,2,0.0,72.9480

---

Check Data Type

In [ ]:
ss.dtypes

Row ID             int64
Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code        int64
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

In [ ]:
ss.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [ ]:
ss.duplicated().sum()

np.int64(0)

In [ ]:
ss.drop (columns='Row ID',inplace=True) # remove column 'Row ID'

In [ ]:
ss['Country'].value_counts()

Country
United States    9994
Name: count, dtype: int64

In [ ]:
ss.drop(columns='Country',inplace=True) # remove column 'Country'

In [ ]:
ss.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       9994 non-null   object
 1   Order Date     9994 non-null   object
 2   Ship Date      9994 non-null   object
 3   Ship Mode      9994 non-null   object
 4   Customer ID    9994 non-null   object
 5   Customer Name  9994 non-null   object
 6   Segment        9994 non-null   object
 7   City           9994 non-null   object
 8   State          9994 non-null   object
 9   Postal Code    9994 non-null   int64
 10  Region         9994 non-null   object
 11  Product ID     9994 non-null   object
 12  Category       9994 non-null   object
 13  Sub-Category   9994 non-null   object
 14  Product Name   9994 non-null   object
 15  Sales          9994 non-null   float64
 16  Quantity       9994 non-null   int64
 17  Discount       9994 non-null   float64
 18  Profit         9994 non-null   float64
dtypes: float64(3), int64(2), object(14)
memory usage: 1.4+ MB

In [ ]:
ss.duplicated().sum()

np.int64(1)

In [ ]:
ss.drop_duplicates(inplace=True)
ss.duplicated().sum()

np.int64(0)

We need change data type for:

-Order Date

-Ship Date

In [ ]:
# Cleaning datatype

ss['Order Date'] = pd.to_datetime(ss['Order Date'])
ss['Ship Date'] = pd.to_datetime(ss['Ship Date'])

In [ ]:
ss.dtypes

Order ID                 object
Order Date       datetime64[ns]
Ship Date        datetime64[ns]
Ship Mode                object
Customer ID              object
Customer Name            object
Segment                  object
City                     object
State                    object
Postal Code               int64
Region                   object
Product ID               object
Category                 object
Sub-Category             object
Product Name             object
Sales                   float64
Quantity                  int64
Discount                float64
Profit                  float64
dtype: object

In [ ]:
ss.shape

(9993, 19)

In [ ]:
ss.columns

Index(['Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID',
       'Customer Name', 'Segment', 'City', 'State', 'Postal Code', 'Region',
       'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Sales',
       'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [ ]:
ss['Cost']  = ss['Sales'] - ss['Profit']
ss.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Cost
0,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,220.0464
1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,512.3580
2,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,7.7486
3,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,1340.6085
4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,19.8516

In [ ]:
ss['Ship Days'] = ss['Ship Date'] - ss['Order Date']
ss.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,Postal Code,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Cost,Ship Days
0,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,Henderson,Kentucky,42420,...,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,220.0464,3 days
1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,Henderson,Kentucky,42420,...,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,512.3580,3 days
2,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,Los Angeles,California,90036,...,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,7.7486,4 days
3,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,Fort Lauderdale,Florida,33311,...,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,1340.6085,7 days
4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,Fort Lauderdale,Florida,33311,...,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,19.8516,7 days

In [ ]:
ss ['Month'] = ss['Order Date'].dt.month_name
# ss['Month'] = ss['Order Date'].dt.strftime('%B')
ss.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,Postal Code,...,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Cost,Ship Days,Month
0,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,Henderson,Kentucky,42420,...,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,220.0464,3 days,November
1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,Henderson,Kentucky,42420,...,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,512.3580,3 days,November
2,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,Los Angeles,California,90036,...,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,7.7486,4 days,June
3,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,Fort Lauderdale,Florida,33311,...,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,1340.6085,7 days,October
4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,Fort Lauderdale,Florida,33311,...,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,19.8516,7 days,October

In [ ]:
ss['Year'] = ss['Order Date'].dt.year



ss

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,Postal Code,...,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Cost,Ship Days,Month,Year
0,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,Henderson,Kentucky,42420,...,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,220.0464,3 days,November,2016
1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,Henderson,Kentucky,42420,...,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,512.3580,3 days,November,2016
2,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,Los Angeles,California,90036,...,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,7.7486,4 days,June,2016
3,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,Fort Lauderdale,Florida,33311,...,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,1340.6085,7 days,October,2015
4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,Fort Lauderdale,Florida,33311,...,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,19.8516,7 days,October,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,CA-2014-110422,2014-01-21,2014-01-23,Second Class,TB-21400,Tom Boeckenhauer,Consumer,Miami,Florida,33180,...,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028,21.1452,2 days,January,2014
9990,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,Costa Mesa,California,92627,...,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332,76.3268,5 days,February,2017
9991,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,Costa Mesa,California,92627,...,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932,239.1828,5 days,February,2017
9992,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,Costa Mesa,California,92627,...,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200,16.2800,5 days,February,2017
9993,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,Westminster,California,92683,...,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480,170.2120,5 days,May,2017

In [ ]:
ss['Category'].value_counts()
ss['Sub-Category'].value_counts()

Sub-Category
Binders        1523
Paper          1370
Furnishings     957
Phones          889
Storage         846
Art             796
Accessories     775
Chairs          616
Appliances      466
Labels          364
Tables          319
Envelopes       254
Bookcases       228
Fasteners       217
Supplies        190
Machines        115
Copiers          68
Name: count, dtype: int64

---

Exploratory Data Analysis (EDA)

1-Top 10 most profit

In [ ]:
top_10_profit = ss.sort_values(by='Profit', ascending=False).head(10)
top_10_profit

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,Postal Code,...,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Cost,Ship Days,Month,Year
6826,CA-2016-118689,2016-10-02,2016-10-09,Standard Class,TC-20980,Tamara Chand,Corporate,Lafayette,Indiana,47905,...,Copiers,Canon imageCLASS 2200 Advanced Copier,17499.950,5,0.0,8399.9760,9099.9740,7 days,October,2016
8153,CA-2017-140151,2017-03-23,2017-03-25,First Class,RB-19360,Raymond Buch,Consumer,Seattle,Washington,98115,...,Copiers,Canon imageCLASS 2200 Advanced Copier,13999.960,4,0.0,6719.9808,7279.9792,2 days,March,2017
4190,CA-2017-166709,2017-11-17,2017-11-22,Standard Class,HL-15040,Hunter Lopez,Consumer,Newark,Delaware,19711,...,Copiers,Canon imageCLASS 2200 Advanced Copier,10499.970,3,0.0,5039.9856,5459.9844,5 days,November,2017
9039,CA-2016-117121,2016-12-17,2016-12-21,Standard Class,AB-10105,Adrian Barton,Consumer,Detroit,Michigan,48205,...,Binders,GBC Ibimaster 500 Manual ProClick Binding System,9892.740,13,0.0,4946.3700,4946.3700,4 days,December,2016
4098,CA-2014-116904,2014-09-23,2014-09-28,Standard Class,SC-20095,Sanjit Chand,Consumer,Minneapolis,Minnesota,55407,...,Binders,Ibico EPK-21 Electric Binding System,9449.950,5,0.0,4630.4755,4819.4745,5 days,September,2014
2623,CA-2017-127180,2017-10-22,2017-10-24,First Class,TA-21385,Tom Ashbrook,Home Office,New York City,New York,10024,...,Copiers,Canon imageCLASS 2200 Advanced Copier,11199.968,4,0.2,3919.9888,7279.9792,2 days,October,2017
509,CA-2015-145352,2015-03-16,2015-03-22,Standard Class,CM-12385,Christopher Martinez,Consumer,Atlanta,Georgia,30318,...,Binders,Fellowes PB500 Electric Punch Plastic Comb Bin...,6354.950,5,0.0,3177.4750,3177.4750,6 days,March,2015
8488,CA-2016-158841,2016-02-02,2016-02-04,Second Class,SE-20110,Sanjit Engle,Consumer,Arlington,Virginia,22204,...,Machines,HP Designjet T520 Inkjet Large Format Printer ...,8749.950,5,0.0,2799.9840,5949.9660,2 days,February,2016
7666,US-2016-140158,2016-10-04,2016-10-08,Standard Class,DR-12940,Daniel Raglin,Home Office,Providence,Rhode Island,2908,...,Copiers,Hewlett Packard LaserJet 3310 Copier,5399.910,9,0.0,2591.9568,2807.9532,4 days,October,2016
6520,CA-2017-138289,2017-01-16,2017-01-18,Second Class,AR-10540,Andy Reiter,Consumer,Jackson,Michigan,49201,...,Binders,GBC DocuBind P400 Electric Binding System,5443.960,4,0.0,2504.2216,2939.7384,2 days,January,2017

2- show OrderID and Customer Name where is Sales > $1000

In [ ]:
ss[['Order ID', 'Customer Name','Sales']][ss['Sales'] > 1000].sort_values(by='Sales', ascending=False).head(10)

            Order ID       Customer Name      Sales
2697  CA-2014-145317         Sean Miller  22638.480
6826  CA-2016-118689        Tamara Chand  17499.950
8153  CA-2017-140151        Raymond Buch  13999.960
2623  CA-2017-127180        Tom Ashbrook  11199.968
4190  CA-2017-166709        Hunter Lopez  10499.970
9039  CA-2016-117121       Adrian Barton   9892.740
4098  CA-2014-116904        Sanjit Chand   9449.950
4277  US-2016-107440        Bill Shonely   9099.930
8488  CA-2016-158841        Sanjit Engle   8749.950
6425  CA-2016-143714  Christopher Conant   8399.976

3- Orders from a specific region (  )

In [ ]:
# ss['Region'].value_counts()
# ss[['Customer Name','City','Category','Sales','Cost','Quantity','Profit','Ship Days']][ss['Region'] == 'West']
# ss[['Customer Name','City','Category','Sales','Cost','Quantity','Profit','Ship Days']][ss['Region'] == 'East']
# ss[['Customer Name','City','Category','Sales','Cost','Quantity','Profit','Ship Days']][ss['Region'] == 'Central']
ss[['Customer Name','City','Category','Sales','Cost','Quantity','Profit','Ship Days']][ss['Region'] == 'South']

,Customer Name,City,Category,Sales,Cost,Quantity,Profit,Ship Days
0,Claire Gute,Henderson,Furniture,261.9600,220.0464,2,41.9136,3 days
1,Claire Gute,Henderson,Furniture,731.9400,512.3580,3,219.5820,3 days
3,Sean O'Donnell,Fort Lauderdale,Furniture,957.5775,1340.6085,5,-383.0310,7 days
4,Sean O'Donnell,Fort Lauderdale,Office Supplies,22.3680,19.8516,2,2.5164,7 days
12,Andrew Allen,Concord,Office Supplies,15.5520,10.1088,3,5.4432,5 days
...,...,...,...,...,...,...,...,...
9971,Mark Packer,Smyrna,Office Supplies,140.7500,98.5250,5,42.2250,4 days
9980,Shaun Weien,Lafayette,Furniture,85.9800,63.6252,1,22.3548,3 days
9987,Ruben Ausman,Athens,Technology,79.9900,51.1936,1,28.7964,4 days
9988,Ruben Ausman,Athens,Technology,206.1000,150.4530,5,55.6470,4 days
9989,Tom Boeckenhauer,Miami,Furniture,25.2480,21.1452,3,4.1028,2 days

4- Which regions or customer segments should we focus on for growth?

South and Central by region

Home Office by Segments

In [58]:
Total_Profit_Region = ss.groupby('Region')['Profit'].sum().sort_values(ascending=False)
Total_Profit_Segments= ss.groupby('Segment')['Profit'].sum().sort_values(ascending=False)
print(Total_Profit_Region)
print(Total_Profit_Segments)

Region
West       108418.4489
East        91534.8388
South       46749.4303
Central     39706.3625
Name: Profit, dtype: float64
Segment
Consumer       134119.2092
Corporate       91979.1340
Home Office     60310.7373
Name: Profit, dtype: float64

5- Total sales by region

In [ ]:
total_salesRegion = ss.groupby('Region')['Sales'].sum().sort_values(ascending=False)
total_salesRegion

Region
West       725457.8245
East       678499.8680
Central    501239.8908
South      391721.9050
Name: Sales, dtype: float64

6- Average profit by category

In [ ]:
avg_Profitbycategory= ss.groupby('Category')['Profit'].mean()
avg_Profitbycategory

Category
Furniture           8.709119
Office Supplies    20.327050
Technology         78.752002
Name: Profit, dtype: float64

7- Which product categories generate the most profit?

In [53]:
category_profit = ss.groupby('Category')['Profit'].sum().sort_values(ascending=False)
print("Product categories by total profit:")
category_profit

Product categories by total profit:

Category
Technology         145454.9481
Office Supplies    122490.8008
Furniture           18463.3316
Name: Profit, dtype: float64

8- Which product category has the highest total sales?

In [ ]:
Highest_total_sales = ss.groupby('Category')['Sales'].sum().max()
Category_1 = ss.groupby('Category')['Sales'].sum().idxmax()
print(f'Product of category has the highest total sales is {Category_1} = {Highest_total_sales}')

Product of category has the highest total sales is Technology = 836154.033

9- Which 'Ship Mode' is used most frequently, and what is its average 'Ship Days'?

In [ ]:
Shop_mode = ss.groupby('Ship Mode') ['Ship Days'].mean()
Shop_mode

Ship Mode
First Class      2 days 04:23:05.695708712
Same Day         0 days 01:03:38.784530386
Second Class     3 days 05:42:47.197943444
Standard Class   5 days 00:09:39.185520362
Name: Ship Days, dtype: timedelta64[ns]

10- What is the total quantity of products sold for each 'Sub-Category'?

In [ ]:
Total_quantity = ss.groupby('Sub-Category')['Quantity'].sum().sort_values(ascending=False)
Total_quantity

Sub-Category
Binders        5974
Paper          5178
Furnishings    3563
Phones         3289
Storage        3158
Art            3000
Accessories    2976
Chairs         2354
Appliances     1729
Labels         1400
Tables         1241
Fasteners       914
Envelopes       906
Bookcases       868
Supplies        647
Machines        440
Copiers         234
Name: Quantity, dtype: int64

11- What is the category that is highest each year?

In [ ]:
#Highest_each_year = ss. groupby(['Year','Category']) ['Sales'].sum()
Highest_each_year = ss. groupby(['Year','Category']) ['Sales'].sum().groupby(level=0).idxmax()
Highest_each_year

Year
2014    (2014, Technology)
2015     (2015, Furniture)
2016    (2016, Technology)
2017    (2017, Technology)
Name: Sales, dtype: object

Saved File

In [59]:
ss.to_csv('/content/Sample - Superstore with Pandas.csv',index= False)